version: "3"
services:
  rest_api:
    container_name: golang-portfolio-api
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - front_end
    env_file:
      - src/api.env
  front_end:
    container_name: vue-portfolio
    image: jbooker10/vue-app-container
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    ports:
      - "80:80"
    volumes:
      - ./nginx_config/nginx:/etc/nginx/conf.d
      - ./nginx_config/certbot/conf:/etc/letsencrypt
      - ./nginx_config/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
