version: "3"
services:
  rest_api:
    container_name: golang-portfolio-api
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - front_end
    env_file:
      - src/api.env
  front_end:
    container_name: vue-portfolio
    image: jbooker10/vue-app-container
    ports:
      - "80:80"
